name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      max-parallel: 12
      matrix:
        os:
          - windows-latest
        java:
          - 8
          - 17
          - 21
        # Support 1-year-old version + latest minor
        maven:
          - 3.6.3
          - 3.9.6
    runs-on: ${{ matrix.os }}
    steps:
      - uses: s4u/setup-maven-action@v1.11.0
        with:
          java-distribution: 'temurin'
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
      - name: Build & Test
        run: mvn --errors --batch-mode --show-version -D"invoker.streamLogsOnFailures" verify
